ht_run: hough_header.h alphas_and_radii.c priors.c prior_parameters.c process_data.c data.c main.c
	gcc -g -o ht_run hough_header.h alphas_and_radii.c priors.c main.c prior_parameters.c process_data.c data.c -g -Wall -I/usr/local/include -L/usr/local/lib -lm -lgsl -lgslcblas 


